### PR TITLE
Custom invariants

### PR DESCRIPTION
**Pull request by lostanlen**
The main purpose of this PR is to extend the structures `archs{1+m}`, whose fields are `banks` and `nonlinearity`, by adding a third field `invariants`. This brings finer control over which invariants are applied at every vertex of the scattering network.
Two invariants are available right now:
- `blurred` (moving average)
- `summed`

The PR is backwards compatible with the current API.

### CODE REVIEW

**Comment by CarmineCella** [comment]
Huge huge work... Ad maiora!

**Comment by CarmineCella** [comment]
Can we work together on monday to integrate it?
Best
C

Il 20/11/15 11:20, Vincent Lostanlen ha scritto:

**Comment by lostanlen** [comment]
Yes I'm available on Monday. What do you mean by "integrating" ?
Have you tried running this new code ? Does it fail on your use case ?
Or do you want to try the new functionalities ?

**Comment by CarmineCella** [comment]
Didn't try yet, working on torch, will do soon.
But wanted to test new features.
I can do it myself if you want.
C

Il 20/11/15 16:19, Vincent Lostanlen ha scritto:

**Pull request merged**
